## Importing Libraries

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
data = pd.read_csv('../data/raw/rainfall_area-wt_sd_1901-2015.csv')

In [36]:
df = data.copy()

In [37]:
df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [38]:
df.shape

(4116, 19)

In [39]:
df.isnull().sum()

SUBDIVISION     0
YEAR            0
JAN             4
FEB             3
MAR             6
APR             4
MAY             3
JUN             5
JUL             7
AUG             4
SEP             6
OCT             7
NOV            11
DEC            10
ANNUAL         26
Jan-Feb         6
Mar-May         9
Jun-Sep        10
Oct-Dec        13
dtype: int64

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4116 entries, 0 to 4115
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SUBDIVISION  4116 non-null   object
 1   YEAR         4116 non-null   int64
 2   JAN          4112 non-null   float64
 3   FEB          4113 non-null   float64
 4   MAR          4110 non-null   float64
 5   APR          4112 non-null   float64
 6   MAY          4113 non-null   float64
 7   JUN          4111 non-null   float64
 8   JUL          4109 non-null   float64
 9   AUG          4112 non-null   float64
 10  SEP          4110 non-null   float64
 11  OCT          4109 non-null   float64
 12  NOV          4105 non-null   float64
 13  DEC          4106 non-null   float64
 14  ANNUAL       4090 non-null   float64
 15  Jan-Feb      4110 non-null   float64
 16  Mar-May      4107 non-null   float64
 17  Jun-Sep      4106 non-null   float64
 18  Oct-Dec      4103 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 611.1+ KB

In [42]:
df.describe()

,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
count,4116.000000,4112.000000,4113.000000,4110.000000,4112.000000,4113.000000,4111.000000,4109.000000,4112.000000,4110.000000,4109.000000,4105.000000,4106.000000,4090.000000,4110.000000,4107.000000,4106.000000,4103.000000
mean,1958.218659,18.957320,21.805325,27.359197,43.127432,85.745417,230.234444,347.214334,290.263497,197.361922,95.507009,39.866163,18.870580,1411.008900,40.747786,155.901753,1064.724769,154.100487
std,33.140898,33.585371,35.909488,46.959424,67.831168,123.234904,234.710758,269.539667,188.770477,135.408345,99.519134,68.685410,42.369611,903.846565,59.308277,201.316965,707.741531,166.942660
min,1901.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.400000,0.000000,0.000000,0.100000,0.000000,0.000000,0.000000,62.300000,0.000000,0.000000,57.400000,0.000000
25%,1930.000000,0.600000,0.600000,1.000000,3.000000,8.600000,70.350000,175.600000,155.975000,100.525000,14.600000,0.700000,0.100000,804.500000,4.100000,24.050000,573.850000,34.200000
50%,1958.000000,6.000000,6.700000,7.800000,15.700000,36.600000,138.700000,284.800000,259.400000,173.900000,65.200000,9.500000,3.000000,1121.300000,19.200000,74.800000,881.100000,98.200000
75%,1987.000000,22.200000,26.800000,31.300000,49.950000,97.200000,305.150000,418.400000,377.800000,265.800000,148.400000,46.100000,17.500000,1644.775000,50.375000,196.950000,1288.175000,213.500000
max,2015.000000,583.700000,403.500000,605.600000,595.100000,1168.600000,1609.900000,2362.800000,1664.600000,1222.000000,948.300000,648.900000,617.500000,6331.100000,699.500000,1745.800000,4536.900000,1252.500000

In [43]:
df = df.sort_values(['SUBDIVISION', 'YEAR']).reset_index(drop=True)

In [44]:
df.head()

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANNUAL,Jan-Feb,Mar-May,Jun-Sep,Oct-Dec
0,ANDAMAN & NICOBAR ISLANDS,1901,49.2,87.1,29.2,2.3,528.8,517.5,365.1,481.1,332.6,388.5,558.2,33.6,3373.2,136.3,560.3,1696.3,980.3
1,ANDAMAN & NICOBAR ISLANDS,1902,0.0,159.8,12.2,0.0,446.1,537.1,228.9,753.7,666.2,197.2,359.0,160.5,3520.7,159.8,458.3,2185.9,716.7
2,ANDAMAN & NICOBAR ISLANDS,1903,12.7,144.0,0.0,1.0,235.1,479.9,728.4,326.7,339.0,181.2,284.4,225.0,2957.4,156.7,236.1,1874.0,690.6
3,ANDAMAN & NICOBAR ISLANDS,1904,9.4,14.7,0.0,202.4,304.5,495.1,502.0,160.1,820.4,222.2,308.7,40.1,3079.6,24.1,506.9,1977.6,571.0
4,ANDAMAN & NICOBAR ISLANDS,1905,1.3,0.0,3.3,26.9,279.5,628.7,368.7,330.5,297.0,260.7,25.4,344.7,2566.7,1.3,309.7,1624.9,630.8

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.isnull().sum()

SUBDIVISION     0
YEAR            0
JAN             4
FEB             3
MAR             6
APR             4
MAY             3
JUN             5
JUL             7
AUG             4
SEP             6
OCT             7
NOV            11
DEC            10
ANNUAL         26
Jan-Feb         6
Mar-May         9
Jun-Sep        10
Oct-Dec        13
dtype: int64

In [47]:
monthly_cols = [
    'JAN', 'FEB', 'MAR', 'APR', 'MAY',
    'JUN', 'JUL', 'AUG', 'SEP',
    'OCT', 'NOV', 'DEC'
]

In [48]:
df[df[monthly_cols].isna().any(axis=1)][
    ['SUBDIVISION', 'YEAR'] + monthly_cols
]

,SUBDIVISION,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
21,ANDAMAN & NICOBAR ISLANDS,1923,79.5,0.0,NaN,91.3,293.5,808.4,636.9,182.2,560.5,131.9,197.4,70.6
22,ANDAMAN & NICOBAR ISLANDS,1924,28.7,0.0,14.8,89.7,191.2,261.2,493.3,290.9,251.2,331.1,378.6,NaN
30,ANDAMAN & NICOBAR ISLANDS,1932,2.8,2.5,10.1,58.2,479.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,ANDAMAN & NICOBAR ISLANDS,1936,16.5,15.3,116.5,NaN,194.3,498.3,664.8,562.9,383.8,174.9,199.2,212.2
40,ANDAMAN & NICOBAR ISLANDS,1942,39.2,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,ANDAMAN & NICOBAR ISLANDS,1947,25.1,111.1,63.2,127.7,206.3,965.6,490.0,293.7,NaN,376.0,67.5,168.6
110,ARUNACHAL PRADESH,1916,48.1,69.8,71.1,316.1,424.6,1124.9,NaN,629.7,333.9,NaN,NaN,NaN
111,ARUNACHAL PRADESH,1917,21.4,164.5,NaN,269.6,107.9,823.8,909.1,628.4,411.5,199.3,63.5,0.0
144,ARUNACHAL PRADESH,1950,38.6,92.8,205.8,425.2,274.2,NaN,377.6,241.8,285.8,356.0,49.5,43.9
147,ARUNACHAL PRADESH,1953,56.4,106.9,236.0,214.9,314.9,409.9,512.5,245.3,449.8,NaN,10.4,23.4
148,ARUNACHAL PRADESH,1957,NaN,NaN,NaN,246.9,448.9,608.1,1219.4,542.6,505.8,146.6,17.1,40.6
153,ARUNACHAL PRADESH,1962,37.2,87.1,45.1,250.3,601.9,1088.8,758.1,1405.9,222.4,255.6,NaN,NaN
778,COASTAL KARNATAKA,2012,NaN,11.4,5.1,77.0,22.9,650.9,754.6,1027.6,382.0,115.1,68.0,3.6
1695,JAMMU & KASHMIR,2009,120.3,117.9,63.7,113.5,64.3,64.1,NaN,96.5,50.5,8.1,NaN,NaN
2049,LAKSHADWEEP,1903,63.5,95.0,0.0,29.5,144.1,212.4,261.8,202.0,292.1,79.1,NaN,NaN
2063,LAKSHADWEEP,1917,NaN,68.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2065,LAKSHADWEEP,1920,82.6,NaN,35.6,49.4,203.1,530.0,134.2,116.9,247.6,258.8,359.6,33.1
2066,LAKSHADWEEP,1921,37.6,0.0,16.8,82.4,156.3,326.2,163.7,235.5,NaN,170.3,110.3,93.0
2072,LAKSHADWEEP,1927,108.2,14.7,40.7,40.4,229.0,181.2,NaN,42.0,256.0,NaN,NaN,NaN
2073,LAKSHADWEEP,1928,42.5,66.6,NaN,1.4,212.3,206.9,268.8,174.9,53.8,124.1,116.3,139.3
2074,LAKSHADWEEP,1929,6.1,66.6,49.5,91.0,248.0,259.3,452.7,34.2,186.3,100.2,NaN,28.8
2076,LAKSHADWEEP,1931,NaN,0.0,0.0,28.5,194.6,262.0,290.4,347.9,167.1,102.0,118.3,96.1
2088,LAKSHADWEEP,1943,112.6,57.4,0.0,NaN,146.0,422.3,346.0,203.1,154.8,309.3,142.8,55.5
2091,LAKSHADWEEP,1946,15.7,1.5,9.5,32.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2094,LAKSHADWEEP,1949,2.2,1.0,0.0,2.4,372.5,380.5,476.7,242.5,188.5,80.1,NaN,8.8
3870,WEST MADHYA PRADESH,2000,0.1,NaN,0.1,0.1,30.1,93.4,320.5,136.2,31.6,1.2,0.0,0.2

In [49]:
data[monthly_cols].isna().sum()

JAN     4
FEB     3
MAR     6
APR     4
MAY     3
JUN     5
JUL     7
AUG     4
SEP     6
OCT     7
NOV    11
DEC    10
dtype: int64

#### Creating Artificial Missing Values

In [50]:
np.random.seed(42)

test_data = data.copy()

evaluation_rows = []

for col in monthly_cols:

    available_indices = test_data.index[
        test_data[col].notna()
    ]

    sample_indices = np.random.choice(
        available_indices,
        size=min(20, len(available_indices)),
        replace=False
    )

    for idx in sample_indices:

        evaluation_rows.append({
            'index': idx,
            'column': col,
            'actual': test_data.loc[idx, col]
        })

        test_data.loc[idx, col] = np.nan

#### Linear Interpolation

In [51]:
linear_data = test_data.sort_values(
    ['SUBDIVISION', 'YEAR']
).copy()

In [52]:
linear_data[monthly_cols] = (
    linear_data
    .groupby('SUBDIVISION')[monthly_cols]
    .transform(
        lambda x: x.interpolate(method='linear')
    )
)

#### Suvdivision-wise Mean

In [53]:
mean_data = test_data.copy()

In [54]:
for col in monthly_cols:

    mean_data[col] = (
        mean_data
        .groupby('SUBDIVISION')[col]
        .transform(
            lambda x: x.fillna(x.mean())
        )
    )

#### KNN

In [55]:
from sklearn.impute import KNNImputer

In [56]:
knn_imputer = KNNImputer(n_neighbors=5)

In [57]:
knn_data = test_data.copy()

knn_data[monthly_cols] = knn_imputer.fit_transform(
    knn_data[monthly_cols]
)

#### Calculate Imputation Errors

In [58]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [59]:
def evaluate_imputation(imputed_data, evaluation_rows):

    actual_values = []
    predicted_values = []

    for item in evaluation_rows:

        idx = item['index']
        col = item['column']
        actual = item['actual']
        predicted = imputed_data.loc[idx, col]

        if pd.notna(predicted):

            actual_values.append(actual)
            predicted_values.append(predicted)

    mae = mean_absolute_error(
        actual_values,
        predicted_values
    )

    rmse = np.sqrt(
        mean_squared_error(
            actual_values,
            predicted_values
        )
    )

    return mae, rmse

#### Comparing all three Methods

In [66]:
linear_mae, linear_rmse = evaluate_imputation(
    linear_data,
    evaluation_rows
)
print("Linear_mae: ",linear_mae)
print("linear_rmse: ",linear_rmse,"\n")

mean_mae, mean_rmse = evaluate_imputation(
    mean_data,
    evaluation_rows
)
print("mean_mae: ",mean_mae)
print("mean_rmse: ",mean_rmse,"\n")

knn_mae, knn_rmse = evaluate_imputation(
    knn_data,
    evaluation_rows
)
print("knn_mae: ",knn_mae)
print("knn_rmse: ",knn_rmse)

Linear_mae:  49.9784518828452
linear_rmse:  84.48417426262046

mean_mae:  44.60396568010289
mean_rmse:  78.13806496683692

knn_mae:  55.23591666666666
knn_rmse:  88.70772547153565

In [67]:
missing_summary = (
    data[data[monthly_cols].isna().any(axis=1)]
    .groupby('SUBDIVISION')[monthly_cols]
    .apply(lambda x: x.isna().sum())
)

missing_summary

,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC
SUBDIVISION,,,,,,,,,,,,
ANDAMAN & NICOBAR ISLANDS,0,0,2,2,1,2,2,2,3,2,2,3
ARUNACHAL PRADESH,1,1,2,0,0,1,1,0,0,2,2,2
COASTAL KARNATAKA,1,0,0,0,0,0,0,0,0,0,0,0
JAMMU & KASHMIR,0,0,0,0,0,0,1,0,0,0,1,1
LAKSHADWEEP,2,1,2,2,2,2,3,2,3,3,6,4
WEST MADHYA PRADESH,0,1,0,0,0,0,0,0,0,0,0,0

In [68]:
missing_summary.sum()

JAN     4
FEB     3
MAR     6
APR     4
MAY     3
JUN     5
JUL     7
AUG     4
SEP     6
OCT     7
NOV    11
DEC    10
dtype: int64

In [69]:
final_data = data.copy()

#### Fill missing monthly rainfall using subdivision-wise mean

In [71]:
for col in monthly_cols:
    final_data[col] = (
        final_data.groupby('SUBDIVISION')[col]
        .transform(lambda x: x.fillna(x.mean()))
    )

In [72]:
final_data[monthly_cols].isna().sum()

JAN    0
FEB    0
MAR    0
APR    0
MAY    0
JUN    0
JUL    0
AUG    0
SEP    0
OCT    0
NOV    0
DEC    0
dtype: int64

#### Recalculated seasonal totals

In [73]:
final_data['Jan-Feb'] = (
    final_data['JAN'] +
    final_data['FEB']
)

final_data['Mar-May'] = (
    final_data['MAR'] +
    final_data['APR'] +
    final_data['MAY']
)

final_data['Jun-Sep'] = (
    final_data['JUN'] +
    final_data['JUL'] +
    final_data['AUG'] +
    final_data['SEP']
)

final_data['Oct-Dec'] = (
    final_data['OCT'] +
    final_data['NOV'] +
    final_data['DEC']
)

#### Recalculate annual rainfall

In [74]:
final_data['ANNUAL'] = final_data[monthly_cols].sum(axis=1)

#### Final Validation

In [77]:
final_data.isna().sum()

SUBDIVISION    0
YEAR           0
JAN            0
FEB            0
MAR            0
APR            0
MAY            0
JUN            0
JUL            0
AUG            0
SEP            0
OCT            0
NOV            0
DEC            0
ANNUAL         0
Jan-Feb        0
Mar-May        0
Jun-Sep        0
Oct-Dec        0
dtype: int64

In [78]:
(final_data[monthly_cols] < 0).sum()

JAN    0
FEB    0
MAR    0
APR    0
MAY    0
JUN    0
JUL    0
AUG    0
SEP    0
OCT    0
NOV    0
DEC    0
dtype: int64

In [79]:
final_data.duplicated(
    subset=['SUBDIVISION', 'YEAR']
).sum()

np.int64(0)

In [81]:
monthly_annual = final_data[monthly_cols].sum(axis=1)

annual_difference = (
    final_data['ANNUAL'] - monthly_annual
)

print(
    "Maximum annual consistency difference:",
    annual_difference.abs().max()
)

Maximum annual consistency difference: 0.0

In [82]:
print("Shape:", final_data.shape)

print(
    "Missing monthly values:",
    final_data[monthly_cols].isna().sum().sum()
)

print(
    "Negative rainfall values:",
    (final_data[monthly_cols] < 0).sum().sum()
)

print(
    "Duplicate subdivision-year rows:",
    final_data.duplicated(
        subset=['SUBDIVISION', 'YEAR']
    ).sum()
)

print(
    "Maximum annual consistency difference:",
    annual_difference.abs().max()
)

Shape: (4116, 19)
Missing monthly values: 0
Negative rainfall values: 0
Duplicate subdivision-year rows: 0
Maximum annual consistency difference: 0.0

In [85]:
final_data.to_csv(
    '../data/processed/rainfall_cleaned.csv',
    index=False
)